CREATE TABLE FrecastState (
    Id INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	Name NVARCHAR (MAX) NOT NULL
);

CREATE TABLE Frecast (
    Id UNIQUEIDENTIFIER DEFAULT (newid()) ROWGUIDCOL NOT NULL PRIMARY KEY,
	Name NVARCHAR (MAX) NOT NULL,
	Owner NVARCHAR (MAX) NOT NULL,
	Description NVARCHAR (MAX),
	Date DATETIME,
	FrecastStateId INT FOREIGN KEY REFERENCES FrecastState(Id)
);

CREATE TABLE FrecastResult (
    Id UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Frecast(Id),
	Result NVARCHAR (MAX) NOT NULL
);

CREATE TABLE FrecastParameters (
    Id UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Frecast(Id),
	Parameters NVARCHAR (MAX) NOT NULL
);

CREATE TABLE FrecastError (
    Id UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Frecast(Id),
	Parameters NVARCHAR (MAX) NOT NULL
);

CREATE TABLE FrecastData (
    Id UNIQUEIDENTIFIER DEFAULT (newid()) ROWGUIDCOL NOT NULL PRIMARY KEY,
	Data NVARCHAR (MAX) NOT NULL,
	FrecastId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Frecast(Id)
);